# permissions for end users to view entanglements.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: entanglement-viewer-role
rules:
- apiGroups:
  - entangle.kairos.io
  resources:
  - entanglements
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - entangle.kairos.io
  resources:
  - entanglements/status
  verbs:
  - get
