# permissions for end users to edit vpns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: vpn-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: entangle
    app.kubernetes.io/part-of: entangle
    app.kubernetes.io/managed-by: kustomize
  name: vpn-editor-role
rules:
- apiGroups:
  - entangle.kairos.io
  resources:
  - vpns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - entangle.kairos.io
  resources:
  - vpns/status
  verbs:
  - get
